_BASE_: "./bases/Base-RCNN-FPN.yaml"
MODEL:
  # COCO ResNet50 weights
  WEIGHTS: "https://dl.fbaipublicfiles.com/detectron2/Misc/cascade_mask_rcnn_R_50_FPN_3x/144998488/model_final_480dd8.pkl"
  MASK_ON: False # Not doing segmentation
  RESNETS:
    DEPTH: 50 # ResNet50
  ROI_HEADS:
    NUM_CLASSES: 2 # Change to suit own task
    NAME: CascadeROIHeads
    # Can reduce this for lower memory/faster training; Default 512
    BATCH_SIZE_PER_IMAGE: 512
  ROI_BOX_HEAD:
    CLS_AGNOSTIC_BBOX_REG: True
  RPN:
    POST_NMS_TOPK_TRAIN: 2000
  BACKBONE:
    FREEZE_AT: 2 # Default 2
DATASETS:
  TRAIN: ("benign_train",)
  TEST: ("benign_test",)
SOLVER:
  IMS_PER_BATCH: 16 # Batch size; Default 16
  BASE_LR: 0.0015
  STEPS: (60000, 80000) # The iteration number to decrease learning rate by GAMMA.
  MAX_ITER: 90000 # Number of training steps
  CHECKPOINT_PERIOD: 2500 # Saves checkpoint every number of steps
INPUT:
  MIN_SIZE_TRAIN: (640, 672, 704, 736, 768, 800) # Image input sizes
TEST:
  # The period (in terms of steps) to evaluate the model during training.
  # Set to 0 to disable.
  EVAL_PERIOD: 2500
OUTPUT_DIR: "./output" # Specify output directory
